### ISSUE TITLE
Tag code with tag 1.5 or correspondent

### ISSUE THREAD

**Issue by gueroverde** [laradock/php-fpm#17]
In docker hub need to build a new version of with tag 1.5-72 or 1.4-72 to be used in laradock laradock repository

**Comment by Mahmoudz** [comment]
@gueroverde thanks for notifying me about this. I just created the tag 2.0 for this repo on Github, and I built and triggered builds (2.0-xx) on hub.docker.com now just waiting the queues to get executed, I will update the tags in the Laradock dockerfiles as soon as the builds finishes execution.

**Comment by Mahmoudz** [comment]
@gueroverde I assume you gonna write support for php 7.2 in the laradock repository, and I also assume the support is gonna be in the form of adding a new `Dockerfile` with thename `php-fpm/Dockerfile-72`. If that's your plan. Could you please take this approach into consideration. 

Instead of a new docker file for each PHP version we can now write a single dockerfile, and add some if-else statements wherever the installation differ between php versions for each tool. 

The only reason why I didn't implement that approach in the past is because of the image tag. There was no way to insert it dynamically, however the newer versions of Docker compose does support this  so instead of doing this `FROM laradock/php-fpm:1.4-72`  we can have something like this `FROM laradock/php-fpm:${PHP_VERSION}`. Which allows us to define the PHP version in the docker compose file and based on that version w'll execute specific parts of the dockerfile via the if-else statements. 

This will have huge benefits for the maintenance fo the files and it helps keeping them consistent.

Kindly let me know what do you think? Best,

**Comment by gueroverde** [comment]
i agree with you, Your assumptions are correct, I wanted to do that, but i prefer the way you  propose. and 
I'm going to work in favor of it, thank you.

Are you already working on it?

How I can help?
 Best regard.

**Comment by Mahmoudz** [comment]
@gueroverde Not really, I'm quiet busy at the moment with private projects, I would love if you can handle this. Best,
